# This workflow will build a docker container, publish it to Docker Hub
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Docker Hub etc.

# This is a basic workflow to help you get started with Actions
name: Build and Publish to DockerHub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a one job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Build the Docker image
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker Image
      run: |-
        docker build --tag "anandkirori/node-app-docker:latest" .
        echo Docker Build Started

    # Push the Docker image to Google Container Registry
    - name: Publish Docker Image
      run: |-
        docker push "anandkirori/node-app-docker:latest"
        echo Docker Publish Started
